version: '3'

# References
# # https://stackoverflow.com/a/60554189/5424025

services:
  mysql:
    image: docker.io/mariadb:10
    environment:
      MARIADB_DATABASE: dbkc
      MARIADB_ROOT_PASSWORD: root
      MARIADB_PASSWORD: admin
      MARIADB_USER: admin
    volumes:
      - my-datavolume:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_ADMIN_URL: localhost
      KC_HOSTNAME_PORT: 8080
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://mysql:3306/dbkc?characterEncoding=UTF-8
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  my-datavolume: