# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hung4898
      MYSQL_DATABASE: mydb
      MYSQL_USER: hungmb
      MYSQL_PASSWORD: hung4898
    ports:
      - "3308:3306"